const cwc2025Album = {
  name: 'FIFA Club World Cup 2025 Panini',
  year: '2025',
  total: 550,
  teams: [
    {
      name: 'Intro',
      country: '',
      stickers: [
        { num: 1, name: 'Logo Panini' },
        { num: 2, name: 'Official Emblem' },
        { num: 3, name: 'Official Trophy' },
        { num: 4, name: 'Official Match Ball' }
      ]
    },
    {
      name: 'SE Palmeiras',
      country: 'br',
      stickers: [
        { num: 5, name: 'Logo' },
        { num: 6, name: 'Weverton' },
        { num: 7, name: 'Joaquín Piquerez' },
        { num: 8, name: 'Murilo' },
        { num: 9, name: 'Gustavo Gómez' },
        { num: 10, name: 'Marcos Rocha' },
        { num: 11, name: 'Richard Ríos' },
        { num: 12, name: 'Aníbal Moreno' },
        { num: 13, name: 'Mauricio' },
        { num: 14, name: 'Raphael Veiga' },
        { num: 15, name: 'Facundo Torres' },
        { num: 16, name: 'Weverton (The Emblem)' },
        { num: 17, name: 'Paulinho' },
        { num: 18, name: 'Estêvão' },
        { num: 19, name: 'Estêvão (The Chosen One)' },
        { num: 20, name: 'José Manuel López' },
        { num: 21, name: 'Felipe Anderson' },
        { num: 22, name: 'Gustavo Gómez (The Crowd Hero)' }
      ]
    },
    {
      name: 'FC Porto',
      country: 'pt',
      stickers: [
        { num: 23, name: 'Logo' },
        { num: 24, name: 'Diogo Costa' },
        { num: 25, name: 'Nehuén Pérez' },
        { num: 26, name: 'Francisco Moura' },
        { num: 27, name: 'Martim Fernandes' },
        { num: 28, name: 'João Mário' },
        { num: 29, name: 'Zé Pedro' },
        { num: 30, name: 'Otávio' },
        { num: 31, name: 'Alan Varela' },
        { num: 32, name: 'Gonçalo Borges' },
        { num: 33, name: 'Stephen Eustaquio' },
        { num: 34, name: 'Diogo Costa (The Emblem)' },
        { num: 35, name: 'Fábio Vieira' },
        { num: 36, name: 'Samu Omorodion' },
        { num: 37, name: 'Samu Omorodion (The Chosen One)' },
        { num: 38, name: 'Pepê' },
        { num: 39, name: 'Danny Namaso' },
        { num: 40, name: 'Alan Varela (The Crowd Hero)' }
      ]
    },
    {
      name: 'Al Ahly',
      country: 'eg',
      stickers: [
        { num: 41, name: 'Logo' },
        { num: 42, name: 'Mohamed El Shenawy' },
        { num: 43, name: 'Ali Maâloul' },
        { num: 44, name: 'Mohamed Hany' },
        { num: 45, name: 'Yasser Ibrahim' },
        { num: 46, name: 'Rami Rabia' },
        { num: 47, name: 'Omar Kamal' },
        { num: 48, name: 'Emam Ashour' },
        { num: 49, name: 'Marawan Attia' },
        { num: 50, name: 'Afsha' },
        { num: 51, name: 'Amr El Solia' },
        { num: 52, name: 'Mohamed El Shenawy (The Emblem)' },
        { num: 53, name: 'Achraf Bencharki' },
        { num: 54, name: 'Wessam Abou Ali' },
        { num: 55, name: 'Wessam Abou Ali (The Chosen One)' },
        { num: 56, name: 'Hussein El Shahat' },
        { num: 57, name: 'Taher Mohamed' },
        { num: 58, name: 'Emam Ashour (The Crowd Hero)' }
      ]
    },
    {
      name: 'Inter Miami',
      country: 'us',
      stickers: [
        { num: 59, name: 'Lionel Messi (The Emblem)' },
        { num: 60, name: 'Benjamin Cremaschi (The Chosen One)' },
        { num: 61, name: 'Luis Suárez (The Crowd Hero)' }
      ]
    },
    {
      name: 'Paris Saint-Germain',
      country: 'fr',
      stickers: [
        { num: 62, name: 'Logo' },
        { num: 63, name: 'Gianluigi Donnarumma' },
        { num: 64, name: 'Achraf Hakimi' },
        { num: 65, name: 'Nuno Mendes' },
        { num: 66, name: 'Marquinhos' },
        { num: 67, name: 'Lucas Beraldo' },
        { num: 68, name: 'Lucas Hernández' },
        { num: 69, name: 'Warren Zaïre-Emery' },
        { num: 70, name: 'João Neves' },
        { num: 71, name: 'Vitinha' },
        { num: 72, name: 'Kang-in Lee' },
        { num: 73, name: 'Vitinha (The Emblem)' },
        { num: 74, name: 'Fabián Ruiz' },
        { num: 75, name: 'Bradley Barcola' },
        { num: 76, name: 'Bradley Barcola (The Chosen One)' },
        { num: 77, name: 'Ousmane Dembélé' },
        { num: 78, name: 'Gonçalo Ramos' },
        { num: 79, name: 'Warren Zaïre-Emery (The Crowd Hero)' }
      ]
    },
    {
      name: 'Atlético de Madrid',
      country: 'es',
      stickers: [
        { num: 80, name: 'Logo' },
        { num: 81, name: 'Jan Oblak' },
        { num: 82, name: 'Robin Le Normand' },
        { num: 83, name: 'Nahuel Molina' },
        { num: 84, name: 'José María Giménez' },
        { num: 85, name: 'Axel Witsel' },
        { num: 86, name: 'Conor Gallagher' },
        { num: 87, name: 'Rodrigo De Paul' },
        { num: 88, name: 'Marcos Llorente' },
        { num: 89, name: 'Koke' },
        { num: 90, name: 'Julián Álvarez' },
        { num: 91, name: 'Koke (The Emblem)' },
        { num: 92, name: 'Samuel Lino' },
        { num: 93, name: 'Antoine Griezmann' },
        { num: 94, name: 'Antoine Griezmann (The Chosen One)' },
        { num: 95, name: 'Alexander Sørloth' },
        { num: 96, name: 'Ángel Correa' },
        { num: 97, name: 'Marcos Llorente (The Crowd Hero)' }
      ]
    },
    {
      name: 'Botafogo',
      country: 'br',
      stickers: [
        { num: 98, name: 'Logo' },
        { num: 99, name: 'John Victor' },
        { num: 100, name: 'Vitinho' },
        { num: 101, name: 'Alexander Barboza' },
        { num: 102, name: 'Bastos' },
        { num: 103, name: 'Jair Cunha' },
        { num: 104, name: 'Mateo Ponte' },
        { num: 105, name: 'Alex Telles' },
        { num: 106, name: 'Cuiabano' },
        { num: 107, name: 'Jefferson Savarino' },
        { num: 108, name: 'Marlon Freitas' },
        { num: 109, name: 'Gregore (The Emblem)' },
        { num: 110, name: 'Gregore' },
        { num: 111, name: 'Igor Jesus' },
        { num: 112, name: 'Igor Jesus (The Chosen One)' },
        { num: 113, name: 'Artur' },
        { num: 114, name: 'Matheus Martins' },
        { num: 115, name: 'Jefferson Savarino (The Crowd Hero)' }
      ]
    },
    {
      name: 'Seattle Sounders',
      country: 'us',
      stickers: [
        { num: 116, name: 'Álex Roldán (The Emblem)' },
        { num: 117, name: 'Jordan Morris (The Chosen One)' },
        { num: 118, name: 'Jesús Ferreira (The Crowd Hero)' }
      ]
    },
    {
      name: 'FC Bayern München',
      country: 'de',
      stickers: [
        { num: 119, name: 'Logo' },
        { num: 120, name: 'Manuel Neuer' },
        { num: 121, name: 'Alphonso Davies' },
        { num: 122, name: 'Dayot Upamecano' },
        { num: 123, name: 'Min-jae Kim' },
        { num: 124, name: 'Raphaël Guerreiro' },
        { num: 125, name: 'Jamal Musiala' },
        { num: 126, name: 'Joshua Kimmich' },
        { num: 127, name: 'Aleksandar Pavlovic' },
        { num: 128, name: 'Harry Kane' },
        { num: 129, name: 'Michael Olise' },
        { num: 130, name: 'Manuel Neuer (The Emblem)' },
        { num: 131, name: 'Leroy Sané' },
        { num: 132, name: 'Serge Gnabry' },
        { num: 133, name: 'Jamal Musiala (The Chosen One)' },
        { num: 134, name: 'Thomas Müller' },
        { num: 135, name: 'Kingsley Coman' },
        { num: 136, name: 'Thomas Müller (The Crowd Hero)' }
      ]
    },
    {
      name: 'Auckland City',
      country: 'nz',
      stickers: [
        { num: 137, name: 'Logo' },
        { num: 138, name: 'Conor Tracey' },
        { num: 139, name: 'Nathan Lobo' },
        { num: 140, name: 'Alfie Rogers' },
        { num: 141, name: 'Adam Mitchell' },
        { num: 142, name: 'Michael den Heijer' },
        { num: 143, name: 'Jordan Vale' },
        { num: 144, name: 'Christian Gray' },
        { num: 145, name: 'Mario Ilich' },
        { num: 146, name: 'Gerard Garriga' },
        { num: 147, name: 'Dylan Manickum' },
        { num: 148, name: 'Mario Ilich (The Emblem)' },
        { num: 149, name: 'Tong Zhou' },
        { num: 150, name: 'Joseph Lee' },
        { num: 151, name: 'Ryan De Vries (The Chosen One)' },
        { num: 152, name: 'Ryan De Vries' },
        { num: 153, name: 'Angus Kilkolly' },
        { num: 154, name: 'Angus Kilkolly (The Crowd Hero)' }
      ]
    },
    {
      name: 'CA Boca Juniors',
      country: 'ar',
      stickers: [
        { num: 155, name: 'Logo' },
        { num: 156, name: 'Agustín Marchesín' },
        { num: 157, name: 'Ayrton Costa' },
        { num: 158, name: 'Marcelo Saracchi' },
        { num: 159, name: 'Luis Advíncula' },
        { num: 160, name: 'Marcos Rojo' },
        { num: 161, name: 'Rodrigo Battaglia' },
        { num: 162, name: 'Tomás Belmonte' },
        { num: 163, name: 'Ander Herrera' },
        { num: 164, name: 'Carlos Palacios' },
        { num: 165, name: 'Exequiel Zeballos' },
        { num: 166, name: 'Edinson Cavani (The Emblem)' },
        { num: 167, name: 'Alan Velasco' },
        { num: 168, name: 'Miguel Merentiel' },
        { num: 169, name: 'Ander Herrera (The Chosen One)' },
        { num: 170, name: 'Edinson Cavani' },
        { num: 171, name: 'Milton Giménez' },
        { num: 172, name: 'Miguel Merentiel (The Crowd Hero)' }
      ]
    },
    {
      name: 'SL Benfica',
      country: 'pt',
      stickers: [
        { num: 173, name: 'Logo' },
        { num: 174, name: 'Anatoliy Trubin' },
        { num: 175, name: 'António Silva' },
        { num: 176, name: 'Tomás Araújo' },
        { num: 177, name: 'Alexander Bah' },
        { num: 178, name: 'Nicolás Otamendi' },
        { num: 179, name: 'Álvaro Carreras' },
        { num: 180, name: 'Orkun Kökçü' },
        { num: 181, name: 'Fredrik Aursnes' },
        { num: 182, name: 'Florentino' },
        { num: 183, name: 'Leandro Barreiro' },
        { num: 184, name: 'Florentino (The Emblem)' },
        { num: 185, name: 'Vangelis Pavlidis' },
        { num: 186, name: 'Kerem Aktürkoğlu' },
        { num: 187, name: 'Ángel Di María (The Chosen One)' },
        { num: 188, name: 'Ángel Di María' },
        { num: 189, name: 'Zeki Amdouni' },
        { num: 190, name: 'Fredrik Aursnes (The Crowd Hero)' }
      ]
    },
    {
      name: 'CR Flamengo',
      country: 'br',
      stickers: [
        { num: 191, name: 'Logo' },
        { num: 192, name: 'Agustín Rossi' },
        { num: 193, name: 'Léo Ortiz' },
        { num: 194, name: 'Léo Pereira' },
        { num: 195, name: 'Alex Sandro' },
        { num: 196, name: 'Wesley França' },
        { num: 197, name: 'Danilo' },
        { num: 198, name: 'Nicolás de la Cruz' },
        { num: 199, name: 'Giorgian de Arrascaeta' },
        { num: 200, name: 'Gerson' },
        { num: 201, name: 'Erick Pulgar' },
        { num: 202, name: 'Giorgian de Arrascaeta (The Emblem)' },
        { num: 203, name: 'Michael' },
        { num: 204, name: 'Pedro' },
        { num: 205, name: 'Gerson (The Chosen One)' },
        { num: 206, name: 'Everton' },
        { num: 207, name: 'Bruno Henrique' },
        { num: 208, name: 'Bruno Henrique (The Crowd Hero)' }
      ]
    },
    {
      name: 'Espérance Sportive de Tunis',
      country: 'tn',
      stickers: [
        { num: 209, name: 'Logo' },
        { num: 210, name: 'Amanallah Memmiche' },
        { num: 211, name: 'Yassine Meriah' },
        { num: 212, name: 'Mohamed Amine Ben Hamida' },
        { num: 213, name: 'Raed Bouchniba' },
        { num: 214, name: 'Mohamed Amine Tougai' },
        { num: 215, name: 'Hamza Jelassi' },
        { num: 216, name: 'Houssem Tka' },
        { num: 217, name: 'Larry Azouni' },
        { num: 218, name: 'Elias Mokwana' },
        { num: 219, name: 'Roger Aholou' },
        { num: 220, name: 'Yassine Meriah (The Emblem)' },
        { num: 221, name: 'Youcef Belaïli' },
        { num: 222, name: 'Yan Sasse' },
        { num: 223, name: 'Rodrigo Rodrigues (The Chosen One)' },
        { num: 224, name: 'Rodrigo Rodrigues' },
        { num: 225, name: 'Zinedine Kada' },
        { num: 226, name: 'Mohamed Amine Ben Hamida (The Crowd Hero)' }
      ]
    },
    {
      name: 'Chelsea FC',
      country: 'gb-eng',
      stickers: [
        { num: 227, name: 'Logo' },
        { num: 228, name: 'Robert Sánchez' },
        { num: 229, name: 'Levi Colwill' },
        { num: 230, name: 'Malo Gusto' },
        { num: 231, name: 'Marc Cucurella' },
        { num: 232, name: 'Wesley Fofana' },
        { num: 233, name: 'Tosin Adarabioyo' },
        { num: 234, name: 'Enzo Fernández' },
        { num: 235, name: 'Moisés Caicedo' },
        { num: 236, name: 'Cole Palmer' },
        { num: 237, name: 'Christopher Nkunku' },
        { num: 238, name: 'Enzo Fernández (The Emblem)' },
        { num: 239, name: 'Nicolas Jackson' },
        { num: 240, name: 'Pedro Neto' },
        { num: 241, name: 'Cole Palmer (The Chosen One)' },
        { num: 242, name: 'Jadon Sancho' },
        { num: 243, name: 'Noni Madueke' },
        { num: 244, name: 'Marc Cucurella (The Crowd Hero)' }
      ]
    },
    {
      name: 'Club León',
      country: 'mx',
      stickers: [
        { num: 245, name: 'Logo' },
        { num: 246, name: 'Alfonso Blanco' },
        { num: 247, name: 'Stiven Barreiro' },
        { num: 248, name: 'Salvador Reyes' },
        { num: 249, name: 'Iván Moreno' },
        { num: 250, name: 'David Ramírez' },
        { num: 251, name: 'Adonis Frías' },
        { num: 252, name: 'Rodrigo Echeverría' },
        { num: 253, name: 'Ángel Estrada' },
        { num: 254, name: 'Sebastián Santos' },
        { num: 255, name: 'Andrés Guardado' },
        { num: 256, name: 'Andrés Guardado (The Emblem)' },
        { num: 257, name: 'Jhonder Cádiz' },
        { num: 258, name: 'James Rodríguez' },
        { num: 259, name: 'Stiven Barreiro (The Chosen One)' },
        { num: 260, name: 'Stiven Mendoza' },
        { num: 261, name: 'Edgar Guerra' },
        { num: 262, name: 'Stiven Mendoza (The Crowd Hero)' }
      ]
    },
    {
      name: 'CA River Plate',
      country: 'ar',
      stickers: [
        { num: 263, name: 'Logo' },
        { num: 264, name: 'Franco Armani' },
        { num: 265, name: 'Fabricio Bustos' },
        { num: 266, name: 'Paulo Díaz' },
        { num: 267, name: 'Lucas Martínez Quarta' },
        { num: 268, name: 'Gonzalo Montiel' },
        { num: 269, name: 'Marcos Acuña' },
        { num: 270, name: 'Enzo Pérez' },
        { num: 271, name: 'Franco Mastantuono' },
        { num: 272, name: 'Santiago Simón' },
        { num: 273, name: 'Nacho Fernández' },
        { num: 274, name: 'Franco Armani (The Emblem)' },
        { num: 275, name: 'Rodrigo Aliendro' },
        { num: 276, name: 'Sebastián Driussi' },
        { num: 277, name: 'Franco Mastantuono (The Chosen One)' },
        { num: 278, name: 'Facundo Colidio' },
        { num: 279, name: 'Miguel Borja' },
        { num: 280, name: 'Gonzalo Montiel (The Crowd Hero)' }
      ]
    },
    {
      name: 'Urawa Red Diamonds',
      country: 'jp',
      stickers: [
        { num: 281, name: 'Logo' },
        { num: 282, name: 'Shusaku Nishikawa' },
        { num: 283, name: 'Marius Høibråten' },
        { num: 284, name: 'Takuya Ogiwara' },
        { num: 285, name: 'Taishi Matsumoto' },
        { num: 286, name: 'Samuel Gustafson' },
        { num: 287, name: 'Matheus Savio' },
        { num: 288, name: 'Ryoma Watanabe' },
        { num: 289, name: 'Kaito Yasui' },
        { num: 290, name: 'Takahiro Sekine' },
        { num: 291, name: 'Shoya Nakajima' },
        { num: 292, name: 'Shusaku Nishikawa (The Emblem)' },
        { num: 293, name: 'Takuro Kaneko' },
        { num: 294, name: 'Genki Haraguchi' },
        { num: 295, name: 'Thiago Santana (The Chosen One)' },
        { num: 296, name: 'Yusuke Matsuo' },
        { num: 297, name: 'Thiago Santana' },
        { num: 298, name: 'Takahiro Sekine (The Crowd Hero)' }
      ]
    },
    {
      name: 'CF Monterrey',
      country: 'mx',
      stickers: [
        { num: 299, name: 'Logo' },
        { num: 300, name: 'Esteban Andrada' },
        { num: 301, name: 'Víctor Guzmán' },
        { num: 302, name: 'Gerardo Arteaga' },
        { num: 303, name: 'Stefan Medina' },
        { num: 304, name: 'Sergio Ramos' },
        { num: 305, name: 'Héctor Moreno' },
        { num: 306, name: 'Nelson Deossa' },
        { num: 307, name: 'Sergio Canales' },
        { num: 308, name: 'Jorge Rodríguez' },
        { num: 309, name: 'Óliver Torres' },
        { num: 310, name: 'Sergio Ramos (The Emblem)' },
        { num: 311, name: 'Germán Berterame' },
        { num: 312, name: 'Lucas Ocampos' },
        { num: 313, name: 'Germán Berterame (The Chosen One)' },
        { num: 314, name: 'Jordi Cortizo' },
        { num: 315, name: 'Jesús Corona' },
        { num: 316, name: 'Sergio Canales (The Crowd Hero)' }
      ]
    },
    {
      name: 'FC Internazionale Milano',
      country: 'it',
      stickers: [
        { num: 317, name: 'Logo' },
        { num: 318, name: 'Yann Sommer' },
        { num: 319, name: 'Alessandro Bastoni' },
        { num: 320, name: 'Federico Dimarco' },
        { num: 321, name: 'Benjamin Pavard' },
        { num: 322, name: 'Denzel Dumfries' },
        { num: 323, name: 'Francesco Acerbi' },
        { num: 324, name: 'Matteo Darmian' },
        { num: 325, name: 'Stefan de Vrij' },
        { num: 326, name: 'Nicolò Barella' },
        { num: 327, name: 'Hakan Çalhanoğlu' },
        { num: 328, name: 'Nicolò Barella (The Emblem)' },
        { num: 329, name: 'Henrikh Mkhitaryan' },
        { num: 330, name: 'Piotr Zieliński' },
        { num: 331, name: 'Lautaro Martínez (The Chosen One)' },
        { num: 332, name: 'Lautaro Martínez' },
        { num: 333, name: 'Marcus Thuram' },
        { num: 334, name: 'Federico Dimarco (The Crowd Hero)' }
      ]
    },
    {
      name: 'Fluminense FC',
      country: 'br',
      stickers: [
        { num: 335, name: 'Logo' },
        { num: 336, name: 'Fábio' },
        { num: 337, name: 'Thiago Silva' },
        { num: 338, name: 'Manoel' },
        { num: 339, name: 'Samuel Xavier' },
        { num: 340, name: 'Thiago Santos' },
        { num: 341, name: 'Matheus Martinelli' },
        { num: 342, name: 'Lima' },
        { num: 343, name: 'Ganso' },
        { num: 344, name: 'Hércules' },
        { num: 345, name: 'Agustín Canobbio' },
        { num: 346, name: 'Fábio (The Emblem)' },
        { num: 347, name: 'Germán Cano' },
        { num: 348, name: 'Keno' },
        { num: 349, name: 'Jhon Arias (The Chosen One)' },
        { num: 350, name: 'Riquelme Felipe' },
        { num: 351, name: 'Jhon Arias' },
        { num: 352, name: 'Thiago Silva (The Crowd Hero)' }
      ]
    },
    {
      name: 'Borussia Dortmund',
      country: 'de',
      stickers: [
        { num: 353, name: 'Logo' },
        { num: 354, name: 'Gregor Kobel' },
        { num: 355, name: 'Nico Schlotterbeck' },
        { num: 356, name: 'Julian Ryerson' },
        { num: 357, name: 'Niklas Süle' },
        { num: 358, name: 'Ramy Bensebaini' },
        { num: 359, name: 'Waldemar Anton' },
        { num: 360, name: 'Julian Brandt' },
        { num: 361, name: 'Marcel Sabitzer' },
        { num: 362, name: 'Emre Can' },
        { num: 363, name: 'Pascal Groß' },
        { num: 364, name: 'Emre Can (The Emblem)' },
        { num: 365, name: 'Serhou Guirassy' },
        { num: 366, name: 'Karim Adeyemi' },
        { num: 367, name: 'Julian Brandt (The Chosen One)' },
        { num: 368, name: 'Julien Duranville' },
        { num: 369, name: 'Jamie Gittens' },
        { num: 370, name: 'Gregor Kobel (The Crowd Hero)' }
      ]
    },
    {
      name: 'Ulsan HD FC',
      country: 'kr',
      stickers: [
        { num: 371, name: 'Logo' },
        { num: 372, name: 'Hyeon-woo Jo' },
        { num: 373, name: 'Seok-ho Hwang' },
        { num: 374, name: 'Sang-woo Kang' },
        { num: 375, name: 'Young-gwon Kim' },
        { num: 376, name: 'Jin-hyun Lee' },
        { num: 377, name: 'Darijan Bojanic' },
        { num: 378, name: 'Hui-gyun Lee' },
        { num: 379, name: 'Seung-beom Ko' },
        { num: 380, name: 'Jae-wook Lee' },
        { num: 381, name: 'Woo-young Jung' },
        { num: 382, name: 'Chung-yong Lee (The Emblem)' },
        { num: 383, name: 'Gustav Ludwigson' },
        { num: 384, name: 'Won-sang Um' },
        { num: 385, name: 'Seung-beom Ko (The Chosen One)' },
        { num: 386, name: 'Yago Cariello' },
        { num: 387, name: 'Chung-yong Lee' },
        { num: 388, name: 'Hyeon-woo Jo (The Crowd Hero)' }
      ]
    },
    {
      name: 'Mamelodi Sundowns',
      country: 'za',
      stickers: [
        { num: 389, name: 'Logo' },
        { num: 390, name: 'Ronwen Williams' },
        { num: 391, name: 'Aubrey Modiba' },
        { num: 392, name: 'Khuliso Mudau' },
        { num: 393, name: 'Thapelo Morena' },
        { num: 394, name: 'Grant Kekana' },
        { num: 395, name: 'Mosa Lebusa' },
        { num: 396, name: 'Malibongwe Khoza' },
        { num: 397, name: 'Terrence Mashego' },
        { num: 398, name: 'Marcelo Allende' },
        { num: 399, name: 'Themba Zwane' },
        { num: 400, name: 'Themba Zwane (The Emblem)' },
        { num: 401, name: 'Peter Shalulile' },
        { num: 402, name: 'Lucas Ribeiro' },
        { num: 403, name: 'Ronwen Williams (The Chosen One)' },
        { num: 404, name: 'Iqraam Rayners' },
        { num: 405, name: 'Tashreeq Matthews' },
        { num: 406, name: 'Lucas Ribeiro (The Crowd Hero)' }
      ]
    },
    {
      name: 'Manchester City',
      country: 'gb-eng',
      stickers: [
        { num: 407, name: 'Logo' },
        { num: 408, name: 'Ederson' },
        { num: 409, name: 'Ruben Dias' },
        { num: 410, name: 'Josko Gvardiol' },
        { num: 411, name: 'Manuel Akanji' },
        { num: 412, name: 'John Stones' },
        { num: 413, name: 'Rodri' },
        { num: 414, name: 'Bernardo Silva' },
        { num: 415, name: 'Kevin De Bruyne' },
        { num: 416, name: 'Ilkay Gundogan' },
        { num: 417, name: 'Mateo Kovacic' },
        { num: 418, name: 'Kevin De Bruyne (The Emblem)' },
        { num: 419, name: 'Omar Marmoush' },
        { num: 420, name: 'Erling Haaland' },
        { num: 421, name: 'Erling Haaland (The Chosen One)' },
        { num: 422, name: 'Phil Foden' },
        { num: 423, name: 'Jeremy Doku' },
        { num: 424, name: 'Phil Foden (The Crowd Hero)' }
      ]
    },
    {
      name: 'Wydad AC',
      country: 'ma',
      stickers: [
        { num: 425, name: 'Logo' },
        { num: 426, name: 'Youssef El Motie' },
        { num: 427, name: 'Jamal Harkass' },
        { num: 428, name: 'Mohamed Moufid' },
        { num: 429, name: 'Abdelmounaim Boutouil' },
        { num: 430, name: 'Ayoub Boucheta' },
        { num: 431, name: 'Saifeddine Bouhra' },
        { num: 432, name: 'Hamza Sakhi' },
        { num: 433, name: 'Arthur Wenderroscky' },
        { num: 434, name: 'Mehdi Moubarik' },
        { num: 435, name: 'Oussama Zemraoui' },
        { num: 436, name: 'Jamal Harkass (The Emblem)' },
        { num: 437, name: 'Ismail Moutaraji' },
        { num: 438, name: 'Pedrinho' },
        { num: 439, name: 'Hamza Sakhi (The Chosen One)' },
        { num: 440, name: 'Cassius Mailula' },
        { num: 441, name: 'Mohamed Rayhi' },
        { num: 442, name: 'Mohamed Moufid (The Crowd Hero)' }
      ]
    },
    {
      name: 'Al-Ain FC',
      country: 'ae',
      stickers: [
        { num: 443, name: 'Logo' },
        { num: 444, name: 'Khalid Eisa' },
        { num: 445, name: 'Kouame Autonne' },
        { num: 446, name: 'Khalid Hashemi' },
        { num: 447, name: 'Erik Menezes' },
        { num: 448, name: 'Solomon Sosu' },
        { num: 449, name: 'Abdoul Karim Traore' },
        { num: 450, name: 'Yahia Nader' },
        { num: 451, name: 'Mohamed Abbas' },
        { num: 452, name: 'Kaku' },
        { num: 453, name: 'Yong-woo Park' },
        { num: 454, name: 'Khalid Eisa (The Emblem)' },
        { num: 455, name: 'Matias Palacios' },
        { num: 456, name: 'Matias Segovia' },
        { num: 457, name: 'Sofiane Rahimi (The Chosen One)' },
        { num: 458, name: 'Mateo Sanabria' },
        { num: 459, name: 'Sofiane Rahimi' },
        { num: 460, name: 'Mateo Sanabria (The Crowd Hero)' }
      ]
    },
    {
      name: 'Juventus FC',
      country: 'it',
      stickers: [
        { num: 461, name: 'Logo' },
        { num: 462, name: 'Michele Di Gregorio' },
        { num: 463, name: 'Bremer' },
        { num: 464, name: 'Andrea Cambiaso' },
        { num: 465, name: 'Federico Gatti' },
        { num: 466, name: 'Weston McKennie' },
        { num: 467, name: 'Teun Koopmeiners' },
        { num: 468, name: 'Khephren Thuram' },
        { num: 469, name: 'Manuel Locatelli' },
        { num: 470, name: 'Douglas Luiz' },
        { num: 471, name: 'Timothy Weah' },
        { num: 472, name: 'Bremer (The Emblem)' },
        { num: 473, name: 'Nico Gonzalez' },
        { num: 474, name: 'Dusan Vlahovic' },
        { num: 475, name: 'Dusan Vlahovic (The Chosen One)' },
        { num: 476, name: 'Kenan Yildiz' },
        { num: 477, name: 'Francisco Conceicao' },
        { num: 478, name: 'Kenan Yildiz (The Crowd Hero)' }
      ]
    },
    {
      name: 'Real Madrid CF',
      country: 'es',
      stickers: [
        { num: 479, name: 'Logo' },
        { num: 480, name: 'Thibaut Courtois' },
        { num: 481, name: 'Eder Militao' },
        { num: 482, name: 'Antonio Rudiger' },
        { num: 483, name: 'Daniel Carvajal' },
        { num: 484, name: 'Jude Bellingham' },
        { num: 485, name: 'Federico Valverde' },
        { num: 486, name: 'Aurelien Tchouameni' },
        { num: 487, name: 'Luka Modric' },
        { num: 488, name: 'Eduardo Camavinga' },
        { num: 489, name: 'Arda Guler' },
        { num: 490, name: 'Luka Modric (The Emblem)' },
        { num: 491, name: 'Vinicius Junior' },
        { num: 492, name: 'Kylian Mbappe' },
        { num: 493, name: 'Vinicius Junior (The Chosen One)' },
        { num: 494, name: 'Endrick' },
        { num: 495, name: 'Rodrygo' },
        { num: 496, name: 'Daniel Carvajal (The Crowd Hero)' }
      ]
    },
    {
      name: 'Al-Hilal',
      country: 'sa',
      stickers: [
        { num: 497, name: 'Logo' },
        { num: 498, name: 'Yassine Bounou' },
        { num: 499, name: 'Joao Cancelo' },
        { num: 500, name: 'Renan Lodi' },
        { num: 501, name: 'Kalidou Koulibaly' },
        { num: 502, name: 'Ali Al-Bulaihi' },
        { num: 503, name: 'Mohamed Kanno' },
        { num: 504, name: 'Ruben Neves' },
        { num: 505, name: 'Sergej Milinkovic-Savic' },
        { num: 506, name: 'Nasser Al-Dawsari' },
        { num: 507, name: 'Kaio Cesar' },
        { num: 508, name: 'Salem Al-Dawsari (The Emblem)' },
        { num: 509, name: 'Aleksandar Mitrovic' },
        { num: 510, name: 'Malcom' },
        { num: 511, name: 'Sergej Milinkovic-Savic (The Chosen One)' },
        { num: 512, name: 'Marcos Leonardo' },
        { num: 513, name: 'Salem Al-Dawsari' },
        { num: 514, name: 'Aleksandar Mitrovic (The Crowd Hero)' }
      ]
    },
    {
      name: 'CF Pachuca',
      country: 'mx',
      stickers: [
        { num: 515, name: 'Logo' },
        { num: 516, name: 'Carlos Moreno' },
        { num: 517, name: 'Bryan Gonzalez' },
        { num: 518, name: 'Sergio Barreto' },
        { num: 519, name: 'Luis Rodriguez' },
        { num: 520, name: 'Gustavo Cabral' },
        { num: 521, name: 'Carlos Sanchez' },
        { num: 522, name: 'Andres Micolta' },
        { num: 523, name: 'Alan Bautista' },
        { num: 524, name: 'Pedro Pedraza' },
        { num: 525, name: 'Elias Montiel' },
        { num: 526, name: 'Gustavo Cabral (The Emblem)' },
        { num: 527, name: 'Arturo Gonzalez' },
        { num: 528, name: 'Oussama Idrissi' },
        { num: 529, name: 'Salomon Rondon (The Chosen One)' },
        { num: 530, name: 'Salomon Rondon' },
        { num: 531, name: 'Owen Gonzalez' },
        { num: 532, name: 'Carlos Moreno (The Crowd Hero)' }
      ]
    },
    {
      name: 'Red Bull Salzburg',
      country: 'at',
      stickers: [
        { num: 533, name: 'Logo' },
        { num: 534, name: 'Alexander Schlager' },
        { num: 535, name: 'Hendry Blank' },
        { num: 536, name: 'Samson Baidoo' },
        { num: 537, name: 'Joane Gadou' },
        { num: 538, name: 'Nicolas Capaldo' },
        { num: 539, name: 'Maurits Kjaergaard' },
        { num: 540, name: 'Takumu Kawamura' },
        { num: 541, name: 'Mads Bidstrup' },
        { num: 542, name: 'Bobby Clark' },
        { num: 543, name: 'Oscar Gloukh' },
        { num: 544, name: 'Maurits Kjaergaard (The Emblem)' },
        { num: 545, name: 'Karim Konate' },
        { num: 546, name: 'Dorgeles Nene' },
        { num: 547, name: 'Oscar Gloukh (The Chosen One)' },
        { num: 548, name: 'Adam Daghim' },
        { num: 549, name: 'Yorbe Vertessen' },
        { num: 550, name: 'Alexander Schlager (The Crowd Hero)' }
      ]
    }
  ]
};
