const PANINI_FUTEBOL_2025_2026 = {
  album: "Futebol 2025-2026",
  country: "Portugal",
  year: "2025",
  publisher: "Panini",
  totalStickers: 497,
  sections: {
    Emblemas: [
      { num: 1, name: "Emblema Alverca", section: "Emblemas", type: "holographic", rookie: false },
      { num: 2, name: "Emblema Arouca", section: "Emblemas", type: "shiny", rookie: false },
      { num: 3, name: "Emblema Aves SAD", section: "Emblemas", type: "shiny", rookie: false },
      { num: 4, name: "Emblema Benfica", section: "Emblemas", type: "shiny", rookie: false },
      { num: 5, name: "Emblema Braga", section: "Emblemas", type: "shiny", rookie: false },
      { num: 6, name: "Emblema Casa Pia", section: "Emblemas", type: "shiny", rookie: false },
      { num: 7, name: "Emblema Estoril", section: "Emblemas", type: "shiny", rookie: false },
      { num: 8, name: "Emblema Estrela da Amadora", section: "Emblemas", type: "shiny", rookie: false },
      { num: 9, name: "Emblema Famalicão", section: "Emblemas", type: "shiny", rookie: false },
      { num: 10, name: "Emblema Gil Vicente", section: "Emblemas", type: "shiny", rookie: false },
      { num: 11, name: "Emblema Moreirense", section: "Emblemas", type: "shiny", rookie: false },
      { num: 12, name: "Emblema Nacional", section: "Emblemas", type: "shiny", rookie: false },
      { num: 13, name: "Emblema Porto", section: "Emblemas", type: "shiny", rookie: false },
      { num: 14, name: "Emblema Rio Ave", section: "Emblemas", type: "shiny", rookie: false },
      { num: 15, name: "Emblema Santa Clara", section: "Emblemas", type: "shiny", rookie: false },
      { num: 16, name: "Emblema Sporting", section: "Emblemas", type: "shiny", rookie: false },
      { num: 17, name: "Emblema Tondela", section: "Emblemas", type: "shiny", rookie: false },
      { num: 18, name: "Emblema Vitória Guimarães", section: "Emblemas", type: "shiny", rookie: false }
    ],

    Alverca: [
      { num: 19, name: "Plantel", section: "Alverca", type: "base", rookie: false },
      { num: 20, name: "André Gomes", section: "Alverca", type: "base", rookie: false },
      { num: 21, name: "Matheus Mendes", section: "Alverca", type: "base", rookie: false },
      { num: 22, name: "Nabil Touaizi", section: "Alverca", type: "base", rookie: false },
      { num: 23, name: "Kaiky Naves", section: "Alverca", type: "base", rookie: false },
      { num: 24, name: "Sergi Gómez", section: "Alverca", type: "base", rookie: false },
      { num: 25, name: "Bastien Meupiyou", section: "Alverca", type: "base", rookie: false },
      { num: 26, name: "Julián Martínez", section: "Alverca", type: "base", rookie: false },
      { num: 27, name: "Francisco Chissumba", section: "Alverca", type: "base", rookie: false },
      { num: 28, name: "Sabit Abdulai", section: "Alverca", type: "base", rookie: false },
      { num: 29, name: "Tomás Mendes", section: "Alverca", type: "base", rookie: true },
      { num: 30, name: "Davy Gui", section: "Alverca", type: "base", rookie: false },
      { num: 31, name: "Alex Amorim", section: "Alverca", type: "foil", rookie: true },
      { num: 32, name: "Lincoln", section: "Alverca", type: "base", rookie: false },
      { num: 33, name: "Chiquinho", section: "Alverca", type: "base", rookie: false },
      { num: 34, name: "Cédric Nuozzi", section: "Alverca", type: "base", rookie: true },
      { num: 35, name: "Lucas Figueiredo", section: "Alverca", type: "base", rookie: false },
      { num: 36, name: "Marezi Marko Milovanović", section: "Alverca", type: "base", rookie: true },
      { num: 37, name: "Sandro Lima", section: "Alverca", type: "base", rookie: false }
    ],

    Arouca: [
      { num: 38, name: "Plantel", section: "Arouca", type: "base", rookie: false },
      { num: 39, name: "João Valido", section: "Arouca", type: "base", rookie: false },
      { num: 40, name: "Nico Mantl", section: "Arouca", type: "base", rookie: false },
      { num: 41, name: "Tiago Esgaio", section: "Arouca", type: "base", rookie: false },
      { num: 42, name: "Alex Pinto", section: "Arouca", type: "base", rookie: false },
      { num: 43, name: "Boris Popović", section: "Arouca", type: "base", rookie: false },
      { num: 44, name: "José Fontán", section: "Arouca", type: "foil", rookie: false },
      { num: 45, name: "Arnau Solà", section: "Arouca", type: "base", rookie: false },
      { num: 46, name: "Amadou Dante", section: "Arouca", type: "base", rookie: false },
      { num: 47, name: "David Simão", section: "Arouca", type: "base", rookie: false },
      { num: 48, name: "Taichi Fukui", section: "Arouca", type: "base", rookie: false },
      { num: 49, name: "Espen van Ee", section: "Arouca", type: "base", rookie: false },
      { num: 50, name: "Pablo Gozálbez", section: "Arouca", type: "base", rookie: false },
      { num: 51, name: "Hyun-ju Lee", section: "Arouca", type: "base", rookie: false },
      { num: 52, name: "Naïs Djouahra", section: "Arouca", type: "base", rookie: false },
      { num: 53, name: "Alfonso Trezza", section: "Arouca", type: "base", rookie: false },
      { num: 54, name: "Iván Barbero", section: "Arouca", type: "base", rookie: false },
      { num: 55, name: "Dylan Nandín", section: "Arouca", type: "base", rookie: true },
      { num: 56, name: "Miguel Puche", section: "Arouca", type: "base", rookie: true }
    ],

    "Avs SAD": [
      { num: 57, name: "Plantel", section: "Avs SAD", type: "base", rookie: false },
      { num: 58, name: "Simão Bertelli", section: "Avs SAD", type: "base", rookie: false },
      { num: 59, name: "João Gonçalves", section: "Avs SAD", type: "base", rookie: false },
      { num: 60, name: "Sidi Bane", section: "Avs SAD", type: "base", rookie: false },
      { num: 61, name: "Guillem Molina", section: "Avs SAD", type: "base", rookie: false },
      { num: 62, name: "Paulo Vitor", section: "Avs SAD", type: "base", rookie: false },
      { num: 63, name: "Cristian Devenish", section: "Avs SAD", type: "base", rookie: false },
      { num: 64, name: "Aderllan Santos", section: "Avs SAD", type: "base", rookie: false },
      { num: 65, name: "Kiki Afonso", section: "Avs SAD", type: "base", rookie: false },
      { num: 66, name: "Tiago Hernández Galletto", section: "Avs SAD", type: "base", rookie: true },
      { num: 67, name: "Gustavo Assunção", section: "Avs SAD", type: "base", rookie: false },
      { num: 68, name: "Jaume Grau", section: "Avs SAD", type: "foil", rookie: false },
      { num: 69, name: "Gustavo Mendonça", section: "Avs SAD", type: "base", rookie: true },
      { num: 70, name: "Pedro Lima", section: "Avs SAD", type: "base", rookie: false },
      { num: 71, name: "Diogo Spencer", section: "Avs SAD", type: "base", rookie: false },
      { num: 72, name: "Óscar Perea", section: "Avs SAD", type: "base", rookie: false },
      { num: 73, name: "Tunde Akinsola", section: "Avs SAD", type: "base", rookie: true },
      { num: 74, name: "Tomané", section: "Avs SAD", type: "base", rookie: false },
      { num: 75, name: "Nenê", section: "Avs SAD", type: "base", rookie: false }
    ],

    Benfica: [
      { num: 76, name: "Plantel", section: "Benfica", type: "base", rookie: false },
      { num: 77, name: "Anatoliy Trubin", section: "Benfica", type: "base", rookie: false },
      { num: 78, name: "Samuel Soares", section: "Benfica", type: "base", rookie: false },
      { num: 79, name: "Alexander Bah", section: "Benfica", type: "base", rookie: false },
      { num: 80, name: "Amar Dedić", section: "Benfica", type: "base", rookie: false },
      { num: 81, name: "António Silva", section: "Benfica", type: "base", rookie: false },
      { num: 82, name: "Nicolás Otamendi", section: "Benfica", type: "base", rookie: false },
      { num: 83, name: "Tomás Araújo", section: "Benfica", type: "base", rookie: false },
      { num: 84, name: "Samuel Dahl", section: "Benfica", type: "base", rookie: false },
      { num: 85, name: "Enzo Barrenechea", section: "Benfica", type: "base", rookie: false },
      { num: 86, name: "Richard Ríos", section: "Benfica", type: "base", rookie: false },
      { num: 87, name: "Fredrik Aursnes", section: "Benfica", type: "base", rookie: false },
      { num: 88, name: "Leandro Barreiro", section: "Benfica", type: "base", rookie: false },
      { num: 89, name: "Gianluca Prestianni", section: "Benfica", type: "base", rookie: false },
      { num: 90, name: "Georgiy Sudakov", section: "Benfica", type: "base", rookie: false },
      { num: 91, name: "Andreas Schjelderup", section: "Benfica", type: "base", rookie: false },
      { num: 92, name: "Dodi Lukébakio", section: "Benfica", type: "base", rookie: false },
      { num: 93, name: "Franjo Ivanović", section: "Benfica", type: "base", rookie: false },
      { num: 94, name: "Vangelis Pavlidis", section: "Benfica", type: "foil", rookie: false }
    ],

    Braga: [
      { num: 95, name: "Plantel", section: "Braga", type: "base", rookie: false },
      { num: 96, name: "Lukáš Horníček", section: "Braga", type: "base", rookie: false },
      { num: 97, name: "Alaa Bellaarouch", section: "Braga", type: "base", rookie: false },
      { num: 98, name: "Víctor Gómez", section: "Braga", type: "base", rookie: false },
      { num: 99, name: "Paulo Oliveira", section: "Braga", type: "base", rookie: false },
      { num: 100, name: "Sikou Niakaté", section: "Braga", type: "base", rookie: false },
      { num: 101, name: "Bright Arrey-Mbi", section: "Braga", type: "base", rookie: false },
      { num: 102, name: "Gustaf Lagerbielke", section: "Braga", type: "base", rookie: true },
      { num: 103, name: "Leonardo Lelo", section: "Braga", type: "base", rookie: false },
      { num: 104, name: "João Moutinho", section: "Braga", type: "base", rookie: false },
      { num: 105, name: "Jean-Baptiste Gorby", section: "Braga", type: "base", rookie: false },
      { num: 106, name: "Florian Grillitsch", section: "Braga", type: "base", rookie: false },
      { num: 107, name: "Rodrigo Zalazar", section: "Braga", type: "base", rookie: false },
      { num: 108, name: "Mario Dorgeles", section: "Braga", type: "base", rookie: false },
      { num: 109, name: "Diego Rodrigues", section: "Braga", type: "base", rookie: true },
      { num: 110, name: "Gabri Martínez", section: "Braga", type: "base", rookie: false },
      { num: 111, name: "Ricardo Horta", section: "Braga", type: "foil", rookie: false },
      { num: 112, name: "Fran Navarro", section: "Braga", type: "base", rookie: false },
      { num: 113, name: "Pau Víctor", section: "Braga", type: "base", rookie: false }
    ],

    "Casa Pia": [
      { num: 114, name: "Plantel", section: "Casa Pia", type: "base", rookie: false },
      { num: 115, name: "Patrick Sequeira", section: "Casa Pia", type: "base", rookie: false },
      { num: 116, name: "Ricardo Batista", section: "Casa Pia", type: "base", rookie: false },
      { num: 117, name: "André Geraldes", section: "Casa Pia", type: "base", rookie: false },
      { num: 118, name: "José Fonte", section: "Casa Pia", type: "base", rookie: false },
      { num: 119, name: "Duplexe Tchamba", section: "Casa Pia", type: "base", rookie: false },
      { num: 120, name: "João Goulart", section: "Casa Pia", type: "base", rookie: false },
      { num: 121, name: "Kaique Rocha", section: "Casa Pia", type: "base", rookie: false },
      { num: 122, name: "Gaizka Larrazabal", section: "Casa Pia", type: "base", rookie: false },
      { num: 123, name: "Seba Sebastián Pérez", section: "Casa Pia", type: "base", rookie: false },
      { num: 124, name: "Iyad Mohamed", section: "Casa Pia", type: "base", rookie: false },
      { num: 125, name: "Yassin Oukili", section: "Casa Pia", type: "base", rookie: true },
      { num: 126, name: "Renato Nhaga", section: "Casa Pia", type: "base", rookie: false },
      { num: 127, name: "Miguel Sousa", section: "Casa Pia", type: "base", rookie: false },
      { num: 128, name: "Jérémy Livolant", section: "Casa Pia", type: "foil", rookie: false },
      { num: 129, name: "Dailon Livramento", section: "Casa Pia", type: "base", rookie: false },
      { num: 130, name: "Cassiano", section: "Casa Pia", type: "base", rookie: false },
      { num: 131, name: "Max Svensson", section: "Casa Pia", type: "base", rookie: false },
      { num: 132, name: "Korede Osundina", section: "Casa Pia", type: "base", rookie: false }
    ],

    Estoril: [
      { num: 133, name: "Plantel", section: "Estoril", type: "base", rookie: false },
      { num: 134, name: "Joel Robles", section: "Estoril", type: "base", rookie: false },
      { num: 135, name: "Martin Turk", section: "Estoril", type: "base", rookie: false },
      { num: 136, name: "Ricard Sánchez", section: "Estoril", type: "base", rookie: false },
      { num: 137, name: "Pedro Carvalho", section: "Estoril", type: "base", rookie: false },
      { num: 138, name: "Kévin Boma", section: "Estoril", type: "base", rookie: false },
      { num: 139, name: "Felix Bacher", section: "Estoril", type: "base", rookie: false },
      { num: 140, name: "Pedro Amaral", section: "Estoril", type: "base", rookie: false },
      { num: 141, name: "Tiago Parente", section: "Estoril", type: "base", rookie: true },
      { num: 142, name: "Patrick de Paula", section: "Estoril", type: "base", rookie: false },
      { num: 143, name: "Jordan Holsgrove", section: "Estoril", type: "base", rookie: false },
      { num: 144, name: "Jandro Orellana", section: "Estoril", type: "base", rookie: false },
      { num: 145, name: "Nodar Lominadze", section: "Estoril", type: "base", rookie: false },
      { num: 146, name: "João Carvalho", section: "Estoril", type: "foil", rookie: false },
      { num: 147, name: "Pizzi", section: "Estoril", type: "base", rookie: false },
      { num: 148, name: "André Lacximicant", section: "Estoril", type: "base", rookie: false },
      { num: 149, name: "Rafik Guitane", section: "Estoril", type: "base", rookie: false },
      { num: 150, name: "Alejandro Marqués", section: "Estoril", type: "base", rookie: false },
      { num: 151, name: "Yanis Begraoui", section: "Estoril", type: "base", rookie: false }
    ],

    "Estrela Amadora": [
      { num: 152, name: "Plantel", section: "Estrela Amadora", type: "base", rookie: false },
      { num: 153, name: "Renan Ribeiro", section: "Estrela Amadora", type: "base", rookie: false },
      { num: 154, name: "Diogo Pinto", section: "Estrela Amadora", type: "base", rookie: false },
      { num: 155, name: "Jefferson Encada", section: "Estrela Amadora", type: "base", rookie: false },
      { num: 156, name: "Bernardo Schappo", section: "Estrela Amadora", type: "foil", rookie: false },
      { num: 157, name: "Luan Patrick", section: "Estrela Amadora", type: "base", rookie: false },
      { num: 158, name: "Atanas Chernev", section: "Estrela Amadora", type: "base", rookie: true },
      { num: 159, name: "Issiar Dramé", section: "Estrela Amadora", type: "base", rookie: false },
      { num: 160, name: "Sidny Lopes Cabral", section: "Estrela Amadora", type: "base", rookie: false },
      { num: 161, name: "Paulo Moreira", section: "Estrela Amadora", type: "base", rookie: true },
      { num: 162, name: "Robinho", section: "Estrela Amadora", type: "base", rookie: false },
      { num: 163, name: "Oumar Ngom", section: "Estrela Amadora", type: "base", rookie: true },
      { num: 164, name: "Jorge Meireles", section: "Estrela Amadora", type: "base", rookie: false },
      { num: 165, name: "Jovane Cabral", section: "Estrela Amadora", type: "base", rookie: false },
      { num: 166, name: "Abraham Marcus", section: "Estrela Amadora", type: "base", rookie: false },
      { num: 167, name: "Ianis Stoica", section: "Estrela Amadora", type: "base", rookie: false },
      { num: 168, name: "Leandro Antonetti", section: "Estrela Amadora", type: "base", rookie: false },
      { num: 169, name: "Kikas", section: "Estrela Amadora", type: "base", rookie: false },
      { num: 170, name: "Rodrigo Pinho", section: "Estrela Amadora", type: "base", rookie: false }
    ],

    Famalicão: [
      { num: 171, name: "Plantel", section: "Famalicão", type: "base", rookie: false },
      { num: 172, name: "Lazar Carević", section: "Famalicão", type: "base", rookie: false },
      { num: 173, name: "Ivan Zlobin", section: "Famalicão", type: "base", rookie: false },
      { num: 174, name: "Rodrigo Pinheiro", section: "Famalicão", type: "base", rookie: false },
      { num: 175, name: "Ibrahima Ba", section: "Famalicão", type: "base", rookie: false },
      { num: 176, name: "Justin de Haas", section: "Famalicão", type: "base", rookie: false },
      { num: 177, name: "Léo Realpe", section: "Famalicão", type: "base", rookie: false },
      { num: 178, name: "Pedro Bondo", section: "Famalicão", type: "base", rookie: false },
      { num: 179, name: "Rafa Soares", section: "Famalicão", type: "base", rookie: false },
      { num: 180, name: "Tom van de Looi", section: "Famalicão", type: "base", rookie: false },
      { num: 181, name: "Mathias de Amorim", section: "Famalicão", type: "base", rookie: false },
      { num: 182, name: "Otar Mamageishvili", section: "Famalicão", type: "base", rookie: false },
      { num: 183, name: "Marcos Peña", section: "Famalicão", type: "base", rookie: false },
      { num: 184, name: "Gustavo Sá", section: "Famalicão", type: "foil", rookie: false },
      { num: 185, name: "Marcos Vinicios Sorriso", section: "Famalicão", type: "base", rookie: false },
      { num: 186, name: "Gil Dias", section: "Famalicão", type: "base", rookie: false },
      { num: 187, name: "Antoine Joujou", section: "Famalicão", type: "base", rookie: false },
      { num: 188, name: "Simon Elisor", section: "Famalicão", type: "base", rookie: false },
      { num: 189, name: "Yassir Zabiri", section: "Famalicão", type: "base", rookie: false }
    ],

    "Gil Vicente": [
      { num: 190, name: "Plantel", section: "Gil Vicente", type: "base", rookie: false },
      { num: 191, name: "Andrew", section: "Gil Vicente", type: "base", rookie: false },
      { num: 192, name: "Dani Figueira", section: "Gil Vicente", type: "base", rookie: false },
      { num: 193, name: "Zé Carlos", section: "Gil Vicente", type: "base", rookie: false },
      { num: 194, name: "Hevertton", section: "Gil Vicente", type: "base", rookie: false },
      { num: 195, name: "Jonathan Buatu", section: "Gil Vicente", type: "base", rookie: false },
      { num: 196, name: "Marvin Elimbi", section: "Gil Vicente", type: "base", rookie: false },
      { num: 197, name: "Ghislain Konan", section: "Gil Vicente", type: "base", rookie: false },
      { num: 198, name: "Jonathan Mutombo", section: "Gil Vicente", type: "base", rookie: false },
      { num: 199, name: "Mohamed Bamba", section: "Gil Vicente", type: "base", rookie: false },
      { num: 200, name: "Facundo Cáseres", section: "Gil Vicente", type: "base", rookie: true },
      { num: 201, name: "Santi García", section: "Gil Vicente", type: "base", rookie: false },
      { num: 202, name: "Luís Esteves", section: "Gil Vicente", type: "base", rookie: false },
      { num: 203, name: "Joelson Fernandes", section: "Gil Vicente", type: "base", rookie: false },
      { num: 204, name: "Sergio Bermejo", section: "Gil Vicente", type: "base", rookie: false },
      { num: 205, name: "Murilo", section: "Gil Vicente", type: "base", rookie: false },
      { num: 206, name: "Gustavo Varela", section: "Gil Vicente", type: "base", rookie: true },
      { num: 207, name: "Martín Fernández", section: "Gil Vicente", type: "base", rookie: false },
      { num: 208, name: "Pablo Felipe", section: "Gil Vicente", type: "foil", rookie: false }
    ],

    Moreirense: [
      { num: 209, name: "Plantel", section: "Moreirense", type: "base", rookie: false },
      { num: 210, name: "Caio Secco", section: "Moreirense", type: "base", rookie: false },
      { num: 211, name: "André Ferreira", section: "Moreirense", type: "base", rookie: false },
      { num: 212, name: "Dinis Pinto", section: "Moreirense", type: "base", rookie: false },
      { num: 213, name: "Diogo Travassos", section: "Moreirense", type: "base", rookie: false },
      { num: 214, name: "Gilberto Batista", section: "Moreirense", type: "base", rookie: false },
      { num: 215, name: "Maracás", section: "Moreirense", type: "base", rookie: false },
      { num: 216, name: "Marcelo", section: "Moreirense", type: "base", rookie: false },
      { num: 217, name: "Kiko Francisco Domingues", section: "Moreirense", type: "base", rookie: false },
      { num: 218, name: "Vasco Sousa", section: "Moreirense", type: "base", rookie: false },
      { num: 219, name: "Mateja Stjepanović", section: "Moreirense", type: "foil", rookie: true },
      { num: 220, name: "Benny Bernardo Martins", section: "Moreirense", type: "base", rookie: false },
      { num: 221, name: "Alan", section: "Moreirense", type: "base", rookie: false },
      { num: 222, name: "Afonso Assis", section: "Moreirense", type: "base", rookie: false },
      { num: 223, name: "Kiko Bondoso", section: "Moreirense", type: "base", rookie: false },
      { num: 224, name: "Cedric Teguía", section: "Moreirense", type: "base", rookie: false },
      { num: 225, name: "Landerson", section: "Moreirense", type: "base", rookie: false },
      { num: 226, name: "Guilherme Schettine", section: "Moreirense", type: "base", rookie: false },
      { num: 227, name: "Yan Maranhão", section: "Moreirense", type: "base", rookie: true }
    ],

    Nacional: [
      { num: 228, name: "Plantel", section: "Nacional", type: "base", rookie: false },
      { num: 229, name: "Lucas França", section: "Nacional", type: "base", rookie: false },
      { num: 230, name: "Kaique Pereira", section: "Nacional", type: "base", rookie: false },
      { num: 231, name: "João Aurélio", section: "Nacional", type: "base", rookie: false },
      { num: 232, name: "Alan Núñez", section: "Nacional", type: "base", rookie: false },
      { num: 233, name: "Ulisses Wilson", section: "Nacional", type: "base", rookie: false },
      { num: 234, name: "Zé Vítor", section: "Nacional", type: "foil", rookie: false },
      { num: 235, name: "Léo Santos", section: "Nacional", type: "base", rookie: false },
      { num: 236, name: "José Gomes", section: "Nacional", type: "base", rookie: false },
      { num: 237, name: "Matheus Dias", section: "Nacional", type: "base", rookie: false },
      { num: 238, name: "Igor Liziero", section: "Nacional", type: "base", rookie: false },
      { num: 239, name: "Joel Silva", section: "Nacional", type: "base", rookie: false },
      { num: 240, name: "Filipe Soares", section: "Nacional", type: "base", rookie: false },
      { num: 241, name: "Chiheb Labidi", section: "Nacional", type: "base", rookie: false },
      { num: 242, name: "Witi Witiness Quembo", section: "Nacional", type: "base", rookie: false },
      { num: 243, name: "Pablo Ruan", section: "Nacional", type: "base", rookie: false },
      { num: 244, name: "Lucas João", section: "Nacional", type: "base", rookie: false },
      { num: 245, name: "Paulinho Bóia", section: "Nacional", type: "base", rookie: false },
      { num: 246, name: "Jesús Chucho Ramírez", section: "Nacional", type: "base", rookie: true }
    ],

    Porto: [
      { num: 247, name: "Plantel", section: "Porto", type: "base", rookie: false },
      { num: 248, name: "Diogo Costa", section: "Porto", type: "base", rookie: false },
      { num: 249, name: "Cláudio Ramos", section: "Porto", type: "base", rookie: false },
      { num: 250, name: "Alberto Costa", section: "Porto", type: "base", rookie: false },
      { num: 251, name: "Martim Fernandes", section: "Porto", type: "base", rookie: false },
      { num: 252, name: "Jan Bednarek", section: "Porto", type: "base", rookie: false },
      { num: 253, name: "Jakub Kiwior", section: "Porto", type: "base", rookie: false },
      { num: 254, name: "Zaidu Sanusi", section: "Porto", type: "base", rookie: false },
      { num: 255, name: "Francisco Moura", section: "Porto", type: "base", rookie: false },
      { num: 256, name: "Alan Varela", section: "Porto", type: "base", rookie: false },
      { num: 257, name: "Pablo Rosario", section: "Porto", type: "base", rookie: false },
      { num: 258, name: "Victor Froholdt", section: "Porto", type: "foil", rookie: true },
      { num: 259, name: "Pepê", section: "Porto", type: "base", rookie: false },
      { num: 260, name: "Rodrigo Mora", section: "Porto", type: "base", rookie: false },
      { num: 261, name: "William Gomes", section: "Porto", type: "base", rookie: false },
      { num: 262, name: "Borja Sainz", section: "Porto", type: "base", rookie: false },
      { num: 263, name: "Deniz Gül", section: "Porto", type: "base", rookie: false },
      { num: 264, name: "Samuel Omorodion Samu Aghehowa", section: "Porto", type: "base", rookie: false },
      { num: 265, name: "Luuk de Jong", section: "Porto", type: "base", rookie: false }
    ],

    "Rio Ave": [
      { num: 266, name: "Plantel", section: "Rio Ave", type: "base", rookie: false },
      { num: 267, name: "Cezary Miszta", section: "Rio Ave", type: "base", rookie: false },
      { num: 268, name: "Kevin Chamorro", section: "Rio Ave", type: "base", rookie: false },
      { num: 269, name: "Marios Vrousai", section: "Rio Ave", type: "base", rookie: false },
      { num: 270, name: "Francisco Petrasso", section: "Rio Ave", type: "base", rookie: false },
      { num: 271, name: "Andreas Ntoi", section: "Rio Ave", type: "base", rookie: false },
      { num: 272, name: "Jakub Brabec", section: "Rio Ave", type: "base", rookie: false },
      { num: 273, name: "Jonathan Panzo", section: "Rio Ave", type: "base", rookie: false },
      { num: 274, name: "Omar Richards", section: "Rio Ave", type: "base", rookie: false },
      { num: 275, name: "Georgios Liavas", section: "Rio Ave", type: "base", rookie: false },
      { num: 276, name: "Tamás Nikitscher", section: "Rio Ave", type: "base", rookie: false },
      { num: 277, name: "João Graça", section: "Rio Ave", type: "base", rookie: false },
      { num: 278, name: "Antonis Papakanellos", section: "Rio Ave", type: "base", rookie: false },
      { num: 279, name: "Brandon Aguilera", section: "Rio Ave", type: "base", rookie: false },
      { num: 280, name: "Ole Pohlmann", section: "Rio Ave", type: "base", rookie: true },
      { num: 281, name: "André Luiz", section: "Rio Ave", type: "base", rookie: false },
      { num: 282, name: "Dario Špikić", section: "Rio Ave", type: "base", rookie: false },
      { num: 283, name: "Marc Gual", section: "Rio Ave", type: "base", rookie: false },
      { num: 284, name: "Clayton", section: "Rio Ave", type: "foil", rookie: false }
    ],

    "Santa Clara": [
      { num: 285, name: "Plantel", section: "Santa Clara", type: "base", rookie: false },
      { num: 286, name: "Gabriel Batista", section: "Santa Clara", type: "base", rookie: false },
      { num: 287, name: "Neneca", section: "Santa Clara", type: "base", rookie: false },
      { num: 288, name: "Lucas Soares", section: "Santa Clara", type: "base", rookie: false },
      { num: 289, name: "Diogo Calila", section: "Santa Clara", type: "base", rookie: false },
      { num: 290, name: "Sidney Lima", section: "Santa Clara", type: "foil", rookie: false },
      { num: 291, name: "Frederico Venâncio", section: "Santa Clara", type: "base", rookie: false },
      { num: 292, name: "Matheus Pereira", section: "Santa Clara", type: "base", rookie: false },
      { num: 293, name: "MT Matheus Araújo", section: "Santa Clara", type: "base", rookie: true },
      { num: 294, name: "Adriano Firmino", section: "Santa Clara", type: "base", rookie: false },
      { num: 295, name: "Pedro Ferreira", section: "Santa Clara", type: "base", rookie: false },
      { num: 296, name: "Serginho", section: "Santa Clara", type: "base", rookie: false },
      { num: 297, name: "Brenner Lucas", section: "Santa Clara", type: "base", rookie: true },
      { num: 298, name: "Gabriel Silva", section: "Santa Clara", type: "base", rookie: false },
      { num: 299, name: "Vinícius Lopes", section: "Santa Clara", type: "base", rookie: false },
      { num: 300, name: "Elias Manoel", section: "Santa Clara", type: "base", rookie: false },
      { num: 301, name: "João Costa", section: "Santa Clara", type: "base", rookie: false },
      { num: 302, name: "Wendel Silva", section: "Santa Clara", type: "base", rookie: false },
      { num: 303, name: "Anthony Carter", section: "Santa Clara", type: "base", rookie: false }
    ],

    Sporting: [
      { num: 304, name: "Plantel", section: "Sporting", type: "base", rookie: false },
      { num: 305, name: "Rui Silva", section: "Sporting", type: "base", rookie: false },
      { num: 306, name: "João Virgínia", section: "Sporting", type: "base", rookie: false },
      { num: 307, name: "Georgios Vagiannidis", section: "Sporting", type: "base", rookie: false },
      { num: 308, name: "Iván Fresneda", section: "Sporting", type: "base", rookie: false },
      { num: 309, name: "Zeno Debast", section: "Sporting", type: "base", rookie: false },
      { num: 310, name: "Ousmane Diomande", section: "Sporting", type: "base", rookie: false },
      { num: 311, name: "Gonçalo Inácio", section: "Sporting", type: "base", rookie: false },
      { num: 312, name: "Maxi Araújo", section: "Sporting", type: "base", rookie: false },
      { num: 313, name: "Morten Hjulmand", section: "Sporting", type: "foil", rookie: false },
      { num: 314, name: "Hidemasa Morita", section: "Sporting", type: "base", rookie: false },
      { num: 315, name: "João Simões", section: "Sporting", type: "base", rookie: false },
      { num: 316, name: "Geovany Quenda", section: "Sporting", type: "base", rookie: false },
      { num: 317, name: "Pedro Gonçalves", section: "Sporting", type: "base", rookie: false },
      { num: 318, name: "Francisco Trincão", section: "Sporting", type: "base", rookie: false },
      { num: 319, name: "Geny Catamo", section: "Sporting", type: "base", rookie: false },
      { num: 320, name: "Alisson Santos", section: "Sporting", type: "base", rookie: true },
      { num: 321, name: "Fotis Ioannidis", section: "Sporting", type: "base", rookie: false },
      { num: 322, name: "Luis Suárez", section: "Sporting", type: "base", rookie: false }
    ],

    Tondela: [
      { num: 323, name: "Plantel", section: "Tondela", type: "base", rookie: false },
      { num: 324, name: "Bernardo Caltabiano", section: "Tondela", type: "base", rookie: false },
      { num: 325, name: "Lucas Cañizares", section: "Tondela", type: "base", rookie: false },
      { num: 326, name: "Bebeto", section: "Tondela", type: "base", rookie: false },
      { num: 327, name: "Tiago Manso", section: "Tondela", type: "base", rookie: false },
      { num: 328, name: "Christian Marques", section: "Tondela", type: "base", rookie: false },
      { num: 329, name: "Brayan Medina", section: "Tondela", type: "base", rookie: false },
      { num: 330, name: "João Afonso", section: "Tondela", type: "base", rookie: false },
      { num: 331, name: "Nor Maviram", section: "Tondela", type: "base", rookie: true },
      { num: 332, name: "Hélder Tavares", section: "Tondela", type: "base", rookie: false },
      { num: 333, name: "Cícero Alves", section: "Tondela", type: "base", rookie: true },
      { num: 334, name: "Joe Hodge", section: "Tondela", type: "base", rookie: false },
      { num: 335, name: "Juanse Rodríguez", section: "Tondela", type: "base", rookie: false },
      { num: 336, name: "Hugo Félix", section: "Tondela", type: "base", rookie: false },
      { num: 337, name: "Yaya Sithole", section: "Tondela", type: "foil", rookie: false },
      { num: 338, name: "Yarlen", section: "Tondela", type: "base", rookie: false },
      { num: 339, name: "Ivan Cavaleiro", section: "Tondela", type: "base", rookie: false },
      { num: 340, name: "Yefrei Rodríguez", section: "Tondela", type: "base", rookie: false },
      { num: 341, name: "Theoson-Jordan Siebatcheu", section: "Tondela", type: "base", rookie: false }
    ],

    "Vitória Guimarães": [
      { num: 342, name: "Plantel", section: "Vitória Guimarães", type: "base", rookie: false },
      { num: 343, name: "Juan Castillo", section: "Vitória Guimarães", type: "base", rookie: false },
      { num: 344, name: "Charles", section: "Vitória Guimarães", type: "base", rookie: false },
      { num: 345, name: "Miguel Maga", section: "Vitória Guimarães", type: "base", rookie: false },
      { num: 346, name: "Rodrigo Abascal", section: "Vitória Guimarães", type: "base", rookie: false },
      { num: 347, name: "Miguel Nóbrega", section: "Vitória Guimarães", type: "base", rookie: false },
      { num: 348, name: "Óscar Rivas", section: "Vitória Guimarães", type: "base", rookie: false },
      { num: 349, name: "Orest Lebedenko", section: "Vitória Guimarães", type: "base", rookie: false },
      { num: 350, name: "João Mendes", section: "Vitória Guimarães", type: "base", rookie: false },
      { num: 351, name: "Beni Mukendi", section: "Vitória Guimarães", type: "base", rookie: false },
      { num: 352, name: "Matija Mitrović", section: "Vitória Guimarães", type: "base", rookie: false },
      { num: 353, name: "Samu", section: "Vitória Guimarães", type: "base", rookie: false },
      { num: 354, name: "Diogo Sousa", section: "Vitória Guimarães", type: "base", rookie: false },
      { num: 355, name: "Miguel Nogueira", section: "Vitória Guimarães", type: "base", rookie: true },
      { num: 356, name: "Noah Saviolo", section: "Vitória Guimarães", type: "base", rookie: false },
      { num: 357, name: "Telmo Arcanjo", section: "Vitória Guimarães", type: "base", rookie: false },
      { num: 358, name: "Gustavo Silva", section: "Vitória Guimarães", type: "base", rookie: false },
      { num: 359, name: "Nélson Oliveira", section: "Vitória Guimarães", type: "foil", rookie: false },
      { num: 360, name: "Alioune Ndoye", section: "Vitória Guimarães", type: "base", rookie: true }
    ],

    Megacraques: [
      { num: 361, name: "Megacraques 361", section: "Megacraques", type: "shiny", rookie: false },
      { num: 362, name: "Megacraques 362", section: "Megacraques", type: "shiny", rookie: false },
      { num: 363, name: "Antonio Silva (Benfica)", section: "Megacraques", type: "shiny", rookie: false },
      { num: 364, name: "Megacraques 364", section: "Megacraques", type: "shiny", rookie: false },
      { num: 365, name: "Barrenechea (Benfica)", section: "Megacraques", type: "shiny", rookie: false },
      { num: 366, name: "Bednarek (Porto)", section: "Megacraques", type: "shiny", rookie: false },
      { num: 367, name: "De Joong (Porto)", section: "Megacraques", type: "shiny", rookie: false },
      { num: 368, name: "Dedic (Benfica)", section: "Megacraques", type: "shiny", rookie: false },
      { num: 369, name: "Diogo Costa (Porto)", section: "Megacraques", type: "shiny", rookie: false },
      { num: 370, name: "Megacraques 370", section: "Megacraques", type: "shiny", rookie: false },
      { num: 371, name: "Victor Froholdt (Porto)", section: "Megacraques", type: "shiny", rookie: true },
      { num: 372, name: "Gabri Veiga (Porto)", section: "Megacraques", type: "shiny", rookie: false },
      { num: 373, name: "Gonçalo Inácio (Sporting)", section: "Megacraques", type: "shiny", rookie: false },
      { num: 374, name: "Gustavo Sà (Famalicão)", section: "Megacraques", type: "shiny", rookie: false },
      { num: 375, name: "Hjulmand (Sporting)", section: "Megacraques", type: "shiny", rookie: false },
      { num: 376, name: "Ioannidis (Sporting)", section: "Megacraques", type: "shiny", rookie: false },
      { num: 377, name: "Megacraques 377", section: "Megacraques", type: "shiny", rookie: false },
      { num: 378, name: "Megacraques 378", section: "Megacraques", type: "shiny", rookie: false },
      { num: 379, name: "Megacraques 379", section: "Megacraques", type: "shiny", rookie: false },
      { num: 380, name: "Maxi Araujo (Sporting)", section: "Megacraques", type: "shiny", rookie: false },
      { num: 381, name: "Nelson Oliveira (Guimarães)", section: "Megacraques", type: "shiny", rookie: false },
      { num: 382, name: "Otamendi (Benfica)", section: "Megacraques", type: "shiny", rookie: false },
      { num: 383, name: "Pablo (Gil Vicente)", section: "Megacraques", type: "shiny", rookie: false },
      { num: 384, name: "Pavlidis (Benfica)", section: "Megacraques", type: "shiny", rookie: false },
      { num: 385, name: "Pedro Gonçalves (Sporting)", section: "Megacraques", type: "shiny", rookie: false },
      { num: 386, name: "Megacraques 386", section: "Megacraques", type: "shiny", rookie: false },
      { num: 387, name: "Ricardo Horta (Braga)", section: "Megacraques", type: "shiny", rookie: false },
      { num: 388, name: "Rodrigo Mora (Porto)", section: "Megacraques", type: "shiny", rookie: false },
      { num: 389, name: "Megacraques 389", section: "Megacraques", type: "shiny", rookie: false },
      { num: 390, name: "Sudakov (Benfica)", section: "Megacraques", type: "shiny", rookie: false },
      { num: 391, name: "Tomás Araújo (Benfica)", section: "Megacraques", type: "shiny", rookie: false },
      { num: 392, name: "Megacraques 392", section: "Megacraques", type: "shiny", rookie: false },
      { num: 393, name: "Megacraques 393", section: "Megacraques", type: "shiny", rookie: false },
      { num: 394, name: "Varela (Porto)", section: "Megacraques", type: "shiny", rookie: false },
      { num: 395, name: "William Gomes (Porto)", section: "Megacraques", type: "shiny", rookie: false },
      { num: 396, name: "Megacraques 396", section: "Megacraques", type: "shiny", rookie: false }
    ],

    Símbolos: [
      { num: 397, name: "David Simão (Arouca)", section: "Símbolos", type: "foil", rookie: false },
      { num: 398, name: "Diogo Costa (Porto)", section: "Símbolos", type: "foil", rookie: false },
      { num: 399, name: "Hjulmand (Sporting)", section: "Símbolos", type: "foil", rookie: false },
      { num: 400, name: "João Aurélio (Nacional)", section: "Símbolos", type: "foil", rookie: false },
      { num: 401, name: "Marcelo (Moreirense)", section: "Símbolos", type: "foil", rookie: false },
      { num: 402, name: "Otamendi (Benfica)", section: "Símbolos", type: "foil", rookie: false },
      { num: 403, name: "Ricardo Horta (Braga)", section: "Símbolos", type: "foil", rookie: false },
      { num: 404, name: "Samu (Guimarães)", section: "Símbolos", type: "foil", rookie: false },
      { num: 405, name: "Zé Carlos (Gil Vicente)", section: "Símbolos", type: "foil", rookie: false }
    ],

    Supersónicos: [
      { num: 406, name: "Alberto Costa (Porto)", section: "Supersónicos", type: "foil", rookie: false },
      { num: 407, name: "André Luiz (Rio Ave)", section: "Supersónicos", type: "foil", rookie: false },
      { num: 408, name: "Brenner Lucas (Santa Clara)", section: "Supersónicos", type: "foil", rookie: true },
      { num: 409, name: "Geny Catamo (Sporting)", section: "Supersónicos", type: "foil", rookie: false },
      { num: 410, name: "Supersónico 410", section: "Supersónicos", type: "foil", rookie: false },
      { num: 411, name: "Livolant (Casa Pia)", section: "Supersónicos", type: "foil", rookie: false },
      { num: 412, name: "Supersónico 412", section: "Supersónicos", type: "foil", rookie: false },
      { num: 413, name: "Telmo Arcanjo (Guimarães)", section: "Supersónicos", type: "foil", rookie: false },
      { num: 414, name: "Tunde Akinsola (Aves)", section: "Supersónicos", type: "foil", rookie: true }
    ],

    Parceiros: [
      { num: 415, name: "Lincoln / Marezi (Alverca)", section: "Parceiros", type: "foil", rookie: false },
      { num: 416, name: "Trezza / Barbero (Arouca)", section: "Parceiros", type: "foil", rookie: false },
      { num: 417, name: "Gustavo Assunçao / Jaume Grau (Aves)", section: "Parceiros", type: "foil", rookie: false },
      { num: 418, name: "Sudakov / Pavlidis (Benfica)", section: "Parceiros", type: "foil", rookie: false },
      { num: 419, name: "Gabri Martínez / Fran Navarro (Braga)", section: "Parceiros", type: "foil", rookie: false },
      { num: 420, name: "Livolant / Cassiano (Casa Pia)", section: "Parceiros", type: "foil", rookie: false },
      { num: 421, name: "Holsgrove / Joao Carvalho (Estoril)", section: "Parceiros", type: "foil", rookie: false },
      { num: 422, name: "Stoica / Kikas (Estrela)", section: "Parceiros", type: "foil", rookie: false },
      { num: 423, name: "Sorriso / Elisor (Famalicão)", section: "Parceiros", type: "foil", rookie: false },
      { num: 424, name: "Luis Esteves / Pablo (Gil Vicente)", section: "Parceiros", type: "foil", rookie: false },
      { num: 425, name: "Alan / Schettine (Moreirense)", section: "Parceiros", type: "foil", rookie: false },
      { num: 426, name: "Boia / Ramirez (Nacional)", section: "Parceiros", type: "foil", rookie: false },
      { num: 427, name: "Borja Sainz / Samu Aghehowa (Porto)", section: "Parceiros", type: "foil", rookie: false },
      { num: 428, name: "André Luiz / Clayton (Rio Ave)", section: "Parceiros", type: "foil", rookie: false },
      { num: 429, name: "Gabriel Silva / Vinicius Lopes (Santa Clara)", section: "Parceiros", type: "foil", rookie: false },
      { num: 430, name: "Trincão / Luis Suarez (Sporting)", section: "Parceiros", type: "foil", rookie: false },
      { num: 431, name: "Cavaleiro / Jordan (Tondela)", section: "Parceiros", type: "foil", rookie: false },
      { num: 432, name: "Gustavo Silva / Nélson Oliveira (Guimarães)", section: "Parceiros", type: "foil", rookie: false }
    ],

    Rookies: [
      { num: 433, name: "Francisco Chissumba (Alverca)", section: "Rookies", type: "shiny", rookie: false },
      { num: 434, name: "Mathias de Amorim (Famalicão)", section: "Rookies", type: "shiny", rookie: false },
      { num: 435, name: "Diego Rodrigues (Braga)", section: "Rookies", type: "shiny", rookie: true },
      { num: 436, name: "Francisco Domingues (Moreirense)", section: "Rookies", type: "shiny", rookie: true },
      { num: 437, name: "Gustavo Varela (Gil Vicente)", section: "Rookies", type: "shiny", rookie: true },
      { num: 438, name: "João Rego (Benfica)", section: "Rookies", type: "shiny", rookie: false },
      { num: 439, name: "João Simões (Sporting)", section: "Rookies", type: "shiny", rookie: false },
      { num: 440, name: "Miguel Nogueira (Guimarães)", section: "Rookies", type: "shiny", rookie: true },
      { num: 441, name: "Tiago Parente (Estoril)", section: "Rookies", type: "shiny", rookie: true }
    ],

    "Mercado de Inverno": [
      { num: 442, name: "Figurina 442", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 443, name: "Figurina 443", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 444, name: "Figurina 444", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 445, name: "Figurina 445", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 446, name: "Figurina 446", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 447, name: "Figurina 447", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 448, name: "Figurina 448", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 449, name: "Figurina 449", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 450, name: "Figurina 450", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 451, name: "Figurina 451", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 452, name: "Figurina 452", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 453, name: "Figurina 453", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 454, name: "Figurina 454", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 455, name: "Figurina 455", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 456, name: "Figurina 456", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 457, name: "Figurina 457", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 458, name: "Figurina 458", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 459, name: "Figurina 459", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 460, name: "Figurina 460", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 461, name: "Figurina 461", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 462, name: "Figurina 462", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 463, name: "Figurina 463", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 464, name: "Figurina 464", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 465, name: "Figurina 465", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 466, name: "Figurina 466", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 467, name: "Figurina 467", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 468, name: "Figurina 468", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 469, name: "Figurina 469", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 470, name: "Figurina 470", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 471, name: "Figurina 471", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 472, name: "Figurina 472", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 473, name: "Figurina 473", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 474, name: "Figurina 474", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 475, name: "Figurina 475", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 476, name: "Figurina 476", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 477, name: "Figurina 477", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 478, name: "Figurina 478", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 479, name: "Figurina 479", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 480, name: "Figurina 480", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 481, name: "Figurina 481", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 482, name: "Figurina 482", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 483, name: "Figurina 483", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 484, name: "Figurina 484", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 485, name: "Figurina 485", section: "Mercado de Inverno", type: "base", rookie: false },
      { num: 486, name: "Figurina 486", section: "Mercado de Inverno", type: "base", rookie: false }
    ],

    Premium: [
      { num: "P-DC", name: "Diogo Costa (Porto)", section: "Premium", type: "foil", rookie: false },
      { num: "P-DL", name: "Dodi Lukébakio (Benfica)", section: "Premium", type: "foil", rookie: false },
      { num: "P-FT", name: "Francisco Trincão (Sporting)", section: "Premium", type: "foil", rookie: false },
      { num: "P-GQ", name: "Geovany Quenda (Sporting)", section: "Premium", type: "foil", rookie: false },
      { num: "P-MH", name: "Morten Hjulmand (Sporting)", section: "Premium", type: "foil", rookie: false },
      { num: "P-NO", name: "Nicolás Otamendi (Benfica)", section: "Premium", type: "foil", rookie: false },
      { num: "P-PF", name: "Pablo Filipe (Gil Vicente)", section: "Premium", type: "foil", rookie: true },
      { num: "P-RZ", name: "Rodrigo Zalazar (Braga)", section: "Premium", type: "foil", rookie: false },
      { num: "P-SO", name: "Samuel Omorodion Samu Aghehowa (Porto)", section: "Premium", type: "foil", rookie: false },
      { num: "P-VF", name: "Victor Froholdt (Porto)", section: "Premium", type: "foil", rookie: true },
      { num: "P-VP", name: "Vangélis Pavlídis (Benfica)", section: "Premium", type: "foil", rookie: false }
    ]
  }
};

if (typeof module !== 'undefined') module.exports = PANINI_FUTEBOL_2025_2026;
